name: solocoding2019_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # 위치(GPS?) 라이브러리 추가
  location: 2.3.5 # https://pub.dartlang.org/packages/location
  # http 통신 라이브러리 추가
  http: 0.12.0+2 # https://pub.dartlang.org/packages/http


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/